version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".cloud/rproxy/conf.d:/etc/nginx/conf.d"
      - ".cloud/rproxy/certs:/etc/nginx/certs:ro"
      - ".cloud/rproxy/vhost.d:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ".cloud/rproxy/html:/usr/share/nginx/html"
      - ".cloud/rproxy/dhparam:/etc/nginx/dhparam"
    networks:
      - app-network

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ".cloud/rproxy/conf.d:/etc/nginx/conf.d"
      - ".cloud/rproxy/certs:/etc/nginx/certs:rw"
      - ".cloud/rproxy/vhost.d:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/tmp/docker.sock"
      - ".cloud/rproxy/html:/usr/share/nginx/html"
      - ".cloud/rproxy/dhparam:/etc/nginx/dhparam"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DEFAULT_EMAIL=eirik@tusenfryd.no
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=https://api.buypass.com/acme/directory
    depends_on:
      - nginx-proxy
    networks:
      - app-network

  hittegods-server:
    build: .cloud/docker
    image: hittegods-serverimg
    depends_on:
      - mysql
      - nginx-proxy
      - nginx-proxy-letsencrypt
    volumes:
      - ./:/application:cached
    networks:
      - app-network

  web:
    image: nginx:stable-alpine
    environment:
      - VIRTUAL_HOST=docker-1.mistet.no
      - LETSENCRYPT_HOST=docker-1.mistet.no
      - LETSENCRYPT_EMAIL=oscar@kolsrudweb.no
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
      - hittegods-server
    networks:
      - app-network

  mysql:
    container_name: database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=pLJ!3?2Z9z+MbnRHNf
      - MYSQL_DATABASE=hittegods
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    volumes:
    - es01:/usr/share/elasticsearch/data
    networks:
      - app-network

  minio:
    container_name: minio
    image: minio/minio
    environment:
      - VIRTUAL_HOST=s.docker-1.mistet.no
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=s.docker-1.mistet.no
      - LETSENCRYPT_EMAIL=oscar@kolsrudweb.no
      - MINIO_ACCESS_KEY=vs8HpUcJ7Uru5YSne9kYepdS4tMhjPae
      - MINIO_SECRET_KEY=Geax8Gcz894d5zK4jwpDxauMMsvG3UfKQqrXfDbQfQ2grbVr
    depends_on:
      - nginx-proxy
      - nginx-proxy-letsencrypt
    volumes:
    - .cloud/minio:/data
    networks:
      - app-network

volumes:
  db-data:
  es01:

networks:
  app-network:
    driver: bridge
